name: main

on:
  workflow_dispatch:
    inputs:
      python:
        description: 'Python version'
        required: true
        default: '3.12'
        type: choice
        options:
          - 3.12
          - 3.13
          - 3.14
          - 3.15
      pyodide:
        description: 'New Pyodide version to build for'
        required: true
        type: string
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python }}
      - name: install pyodide build
        run: pip install pyodide-build==${{ inputs.pyodide }} wheel-filename
      - name: Get emscripten version
        run: |
          # import here will download the pyodide xbuild env which outputs a line to
          # stdout, hence the tail -1
          python -c 'from pyodide_build.build_env import emscripten_version;print(f"EMVERSION={emscripten_version()}")' | tail -1 >> $GITHUB_ENV
      - name: Install emsdk ${{env.EMVERSION}}
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EMVERSION}}
          actions-cache-folder: 'emsdk-cache'
      - name: Arrow build
        run: |
          sudo apt-get install ninja-build
          pyodide build-recipes-no-deps --recipe-dir . pyarrow
      - name: Get info from built wheel file
        run: |
          # get arrow version and wheel name and make metafile
          ARROW_WHEEL=$(basename pyarrow/dist/*.whl)
          ARROW_VERSION=$(wheel-filename ${ARROW_WHEEL} | jq -r '.version')
          ARROW_SHA256=$(sha256sum pyarrow/dist/*.whl | cut -d ' ' -f 1)
          echo ARROW_WHEEL=${ARROW_WHEEL}>>$GITHUB_ENV
          echo ARROW_VERSION=${ARROW_VERSION}>>$GITHUB_ENV
          echo ARROW_SHA256=${ARROW_SHA256}>>$GITHUB_ENV
          echo ARROW_RELEASE_URL=https://github.com/${{ github.repository_owner }}/${{ github.repository }}/releases/download/${{ inputs.pyodide }}/${ARROW_WHEEL}
          sed "s:#RELEASE_URL#:${ARROW_RELEASE_URL}:g;s:#RELEASE_SHA256#:${ARROW_SHA256}:g;s:#RELEASE_VERSION#:${ARROW_VERSION}:g;"\
           < pyarrow/_meta_built_template.yaml > pyarrow/dist/${ARROW_WHEEL}.yaml
      - name: Upload the build artifacts for build debugging purposes
        uses: actions/upload-artifact@v4
        with:
          name: build_wheel
          path: pyarrow/dist
          retention-days: 1
      - name: Create release 
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.pyodide }}
          name: Build of Arrow for pyodide ${{ inputs.pyodide}}. pyarrow version = ${{env.ARROW_VERSION}}
          artifacts: pyarrow/dist/*
          replacesArtifacts: true
          allowUpdates: true
          updateOnlyUnreleased: true
          prerelease: true

