name: main

on:
  workflow_dispatch:
    inputs:
      pyodide:
        description: 'New Pyodide version to build for (or latest)'
        required: true
        type: string
        default: latest
permissions:
  contents: write

jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get pyodide nightly xbuildenv url
        if: inputs.pyodide == 'latest'
        uses: robinraju/release-downloader@v1
        with:
          repository: 'pyodide/pyodide-build-environment-nightly'
          latest: true
          fileName: '*tar*'
          out-file-path: .build_env
          extract: false
      - name: Get xbuild environment from pyodide json
        if: inputs.pyodide != 'latest'
        run: |
          wget https://raw.githubusercontent.com/pyodide/pyodide/main/pyodide-cross-build-environments.json
          emscripten_ver=$(jq -r ".releases | .[\"${{ inputs.pyodide }}\"]| .emscripten_version" pyodide-cross-build-environments.json)
          python_ver=$(jq -r ".releases | .[\"${{ inputs.pyodide }}\"]| .python_version" pyodide-cross-build-environments.json)
          min_pyodide_build=$(jq -r ".releases | .[\"${{ inputs.pyodide }}\"]| .min_pyodide_build_version" pyodide-cross-build-environments.json)
          xbuild_url=$(jq -r ".releases | .[\"${{ inputs.pyodide }}\"]| .url" pyodide-cross-build-environments.json)
          mkdir .build_env
          cd .build_env
          wget ${xbuild_url}         
      - name: Get python etc. versions from xbuild environment
        run: |
          cd .build_env
          tar -xjf *.tar.*
          makefile_envs=$(find . -name Makefile.envs | tail -n 1)
          echo "PYVER=$(grep 'export PYVERSION ?=' ${makefile_envs} | cut -d' ' -f4)"  >> "$GITHUB_ENV"
          echo "EMVER=$(grep 'export PYODIDE_EMSCRIPTEN_VERSION ?=' ${makefile_envs} | cut -d' ' -f4)"  >> "$GITHUB_ENV"
          echo "ACTUAL_PYODIDE_VERSION=$(grep 'export PYODIDE_VERSION ?=' ${makefile_envs} | cut -d' ' -f4)"  >> "$GITHUB_ENV"
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYVER }}
      - name: install pyodide build and set xbuild environment
        run: pip install pyodide-build wheel-filename
             pyodide xbuildenv install .build_env/*.tar.*
      - name: Install emsdk ${{env.EMVER}}
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EMVER}}
          actions-cache-folder: 'emsdk-cache'
      - name: Arrow build
        run: |
          sudo apt-get install ninja-build
          pyodide build-recipes-no-deps --recipe-dir . pyarrow
      - name: Get info from built wheel file
        run: |
          # get arrow version and wheel name and make metafile
          ARROW_WHEEL=$(basename pyarrow/dist/*.whl)
          ARROW_VERSION=$(wheel-filename ${ARROW_WHEEL} | jq -r '.version')
          ARROW_SHA256=$(sha256sum pyarrow/dist/*.whl | cut -d ' ' -f 1)
          ARROW_RELEASE_URL=https://github.com/${{ github.repository }}/releases/download/${{ inputs.pyodide }}/${ARROW_WHEEL}
          echo ARROW_WHEEL=${ARROW_WHEEL}>>$GITHUB_ENV
          echo ARROW_VERSION=${ARROW_VERSION}>>$GITHUB_ENV
          echo ARROW_SHA256=${ARROW_SHA256}>>$GITHUB_ENV
          # use ^ as separator for sed call below, because most of the normal ones are
          # either special characters in bash or URL characters
          sed "s^#RELEASE_URL#^${ARROW_RELEASE_URL}^g;s^#RELEASE_SHA256#^${ARROW_SHA256}^g;s^#RELEASE_VERSION#^${ARROW_VERSION}^g;"\
           < pyarrow/_meta_built_template.yaml > pyarrow/dist/${ARROW_WHEEL}.yaml
      - name: Upload the build artifacts for build debugging purposes
        uses: actions/upload-artifact@v4
        with:
          name: build_wheel
          path: pyarrow/dist
          retention-days: 1
      - name: Create release 
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.ACTUAL_PYODIDE_VERSION }}
          name: Build of Arrow for pyodide ${{ env.ACTUAL_PYODIDE_VERSION}}. pyarrow version = ${{env.ARROW_VERSION}}
          artifacts: pyarrow/dist/*
          replacesArtifacts: true
          allowUpdates: true
          updateOnlyUnreleased: true
          prerelease: true

